<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project>
    <!-- Переопределение выходных путей -->
    <PropertyGroup>
        <OutDir>$(SolutionDir)bin\$(Platform)\$(Configuration)\</OutDir>
        <IntDir>$(SolutionDir)obj\$(MSBuildProjectName)\$(Platform)\$(Configuration)\</IntDir>
    </PropertyGroup>
</Project>
