<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project>
    <PropertyGroup>
        <MpiExecBinaries>$(ProgramFiles)\Microsoft MPI\Bin</MpiExecBinaries>
    </PropertyGroup>

    <ItemGroup>
        <ReferenceCopyLocalPaths Include="$(MpiExecBinaries)\mpiexec.exe" />
        <ReferenceCopyLocalPaths Include="$(MpiExecBinaries)\smpd.exe" />
        <ReferenceCopyLocalPaths Include="$(SystemRoot)\System32\msmpi.dll" />
    </ItemGroup>
</Project>
